[option]
  document = '8pt'

[profile]
  name = 'Kye W. Shi'
  address = ['340 E Foothill Blvd, Box 705',
             'Claremont, CA 91711']
  links = ['kwshi@hmc.edu',
           'github.com/kwshi',
           'linkedin.com/in/kwshi']
  phone = ['(630) 824-7713']

[[section]]
  title = 'Education'
  [[section.subsection]]
    title = 'Harvey Mudd College'
    location = 'Claremont, CA'
    date = 'Aug. 2017--(May 2021)'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['B.S. in Mathematica \& Computer Science',
              'Relevant coursework:']
    [[section.subsection.body]]
      type = 'itemize'
      item = ['Principles \& Practice of Computer Science (2017 Fall)',
              'Multivariable Calculus (2017 Fall)',
              'Computability \& Logic (2018 Spring)']
  [[section.subsection]]
    title = 'Monte Vista Christian School'
    location = 'Watsonville, CA'
    date = 'Aug. 2014--May 2017'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['Salutatorian, GPA 4.5 (unweighted 4.0)',
              'Relevant coursework:']
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      item = ['Digital Electronics (2016 Fall--2017 Spring)']

[[section]]
  title = 'Skills'
  [[section.subsection]]
    title = 'Languages'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['Fluent: Python, \LaTeX',
              'Familiar: Go, Bash, HTML/CSS',
              'Basics: Java, Javascript, Rust, C/C++']
  [[section.subsection]]
    title = 'Software/Hardware'
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      item = ['Arch Linux (home, servers)',
              'OpenSCAD (personal projects)',
              'Arduino (personal projects)',
              'Raspberry Pi (mini servers)',
              '3D printers']

[[section]]
  title = 'Projects'
  [[section.subsection]]
    title = 'Totem (iOS app)'
    date = 'Sep.--Nov. 2014'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['Developed periodic table iOS app that provided a comprehensive database of properties about the elements',
              'Over 3K downloads from users in U.S., Canada, Philippines, Thailand, and U.K.']
      
    

[[section]]
  title = 'Research'
  [[section.subsection]]
    title = 'Yale Summer Program in Astrophysics'
    location ='New Haven, CT'
    date = 'Jul.--Aug. 2016'
    [[section.subsection.body]]
      type = 'paragraph'
      item = 'Relevant skills:'
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      item = ['Asteroid observation',
              'Asteroid trajectory regression',
              'Python (NumPy, SciPy)',
              'Statistical data analysis',
              'Basic genetic algorithms']

[[section]]
  title = 'Leadership'
  [[section.subsection]]
    title = 'Unpaid tutoring'
    date = '2015--Present'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['Volunteered to tutor high school peers in physics, economics, and math']
    [[section.subsection.body]]
      type = 'itemize'
      item = 'Helped to significantly improve near-failing student grades'
  [[section.subsection]]
    title = 'VEX robotics competition'
    location = 'High school'
    date = 'Sep. 2016--Feb. 2017'
    [[section.subsection.body]]
      type = 'paragraph'
      item = 'Helped mentor peers in ROBOTC programming'

[[section]]
  title = 'Activities'
  [[section.subsection]]
    title = 'MathILy'
    location = 'Bryn Mawr, PA'
    [[section.subsection.body]]
      type = 'paragraph'
      item = ['5-week inquiry-based mathematics exploration summer program',
               'Relevant topics:']
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      item = ['Linear algebra',
              'Abstract algebra',
              'Graph theory',
              'Complex analysis',
              'Knot theory',
              'Projective geometry',
              'Number theory',
              'Applications in origami']

[[section]]
  title = 'Achievements'
  [[section.subsection]]
    title = 'U.S. National Physics Olympiad'
    date = 'Apr. 2016, 2017'
    summary = 'Gold medal'
  [[section.subsection]]
    title = 'International Physics Olympiad'
    date = 'Jul. 2017'
    summary = 'U.S. team traveler (one of five); Gold medal'
  [[section.subsection]]
    title = 'ACM Intercollegiate Programming Competition (ICPC)'
    date = 'Nov. 2017'
    summary = 'Southern California regional competition; 11\textsuperscript{th} place (team of three)'
      
      
