[profile]
  name = 'Kye W. Shi'
  address = ['340 E Foothill Blvd, Box 705',
             'Claremont, CA 91711']
  links = ['kwshi@hmc.edu',
           'github.com/kwshi',
           'linkedin.com/in/kwshi']
  phone = ['(630) 824-7713']

[[section]]
  title = 'Education'
  
  [[section.subsection]]
    title = 'Harvey Mudd College'
    location = 'Claremont, CA'
    date = 'Aug. 2017--(May 2021)'
    [[section.subsection.body]]
      type = 'paragraph'
      items = ['B.S. in Mathematica & Computer Science',
               'Relevant coursework:']
    [[section.subsection.body]]
      type = 'itemize'
      items = ['Principles & Practice of Computer Science (2017 Fall)',
               'Multivariable Calculus (2017 Fall)',
               'Computability & Logic (2018 Spring)']
               
  [[section.subsection]]
    title = 'Monte Vista Christian School'
    location = 'Watsonville, CA'
    date = 'Aug. 2014--May 2017'
    [[section.subsection.body]]
      type = 'paragraph'
      content = ['Salutatorian, GPA 4.5 (unweighted 4.0)',
                 'Relevant coursework:']
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      items = ['Digital Electronics (2016 Fall--2017 Spring)']

[[section]]
  title = 'Skills'

  [[section.subsection]]
    title = 'Languages'
    [[section.subsection.body]]
      type = 'paragraph'
      items = ['Fluent: Python, \LaTeX',
               'Familiar: Go, Bash, HTML/CSS',
               'Basics: Java, Javascript, Rust, C/C++']

  [[section.subsection]]
    title = 'Software/Hardware'
    [[section.subsection.body]]
      type = 'itemize'
      columns = 2
      items = ['Arch Linux (home, servers)',
               'OpenSCAD (personal projects)',
               'Arduino (personal projects)',
               'Raspberry Pi (mini servers)']

[[section]]
  title = 'Research'

  [[section.subsection]]
    